version: "3"

services:
  app:
    build: .docker/app
    entrypoint: .docker/app/entrypoint.sh
    container_name: bank-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/db
    container_name: bank-db
    restart: always
    tty: true
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bank_db
